const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi))new vm.Script(m[1]);
function fn(name){const start=html.search(new RegExp('^function '+name+'\\(','m'));assert(start>=0);const tail=html.slice(start);const end=tail.slice(1).search(/^(?:function |async function |let |const |window\.|setInterval\(|load\()/m);return tail.slice(0,end+1);}
let seq=0,undo;const alerts=[];
const ctx={Blob,S:{memo:[{id:'memo1',text:'護照',cat:'證件',done:false}],trash:{}},FM:{},TI:()=>'',esc:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),uid:()=>`buy${++seq}`,alert:m=>alerts.push(m),confirm:()=>true,openModal:()=>{},setD:u=>Object.assign(ctx.S,u),tomb:id=>ctx.S.trash[id]=Date.now(),undoToast:(_,f)=>undo=f};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf("let buyFilter='all'"),html.indexOf('function memoView()')),ctx);
vm.runInContext(fn('toggleMemo'),ctx);
vm.runInContext(fn('stampChanges'),ctx);vm.runInContext(fn('_itemSig'),ctx);vm.runInContext(fn('mergeById'),ctx);
ctx.FM={buyName:'餅乾',buyQuantity:2,buyShop:'河口湖',buyNote:'送家人'};ctx.saveBuy();
assert.equal(ctx.buyItems().length,1);assert.equal(ctx.S.memo[0].text,'護照');const id=ctx.buyItems()[0].id;
ctx.openBuy(null,id);ctx.FM.buyName='新口味';ctx.saveBuy();assert.equal(ctx.buyItems()[0].text,'新口味');assert.equal(ctx.buyItems()[0].quantity,2);
ctx.toggleMemo(id);assert.equal(ctx.buyItems()[0].done,true);
ctx.openBuy(null,id);ctx.FM.buyNote='改備註';ctx.saveBuy();assert.equal(ctx.buyItems()[0].done,true);
ctx.FM={buyName:' ',buyQuantity:1};ctx.saveBuy();ctx.FM={buyName:'錯誤數量',buyQuantity:1.5};ctx.saveBuy();assert.equal(alerts.length,2);assert.equal(ctx.buyItems().length,1);
ctx.S.memo.push({id:'xss',kind:'purchase',text:'<img onerror=alert(1)>',note:'<script>',quantity:1,done:false});assert(!ctx.buyView().includes('<img onerror'));assert(ctx.buyView().includes('&lt;script>'));
vm.runInContext("buyFilter='pending'",ctx);assert(!ctx.buyView().includes('新口味'));vm.runInContext("buyFilter='done'",ctx);assert(ctx.buyView().includes('新口味'));
const stamped=ctx.stampChanges(ctx.S.memo,[]);assert(stamped.every(m=>m._u));const restored=JSON.parse(JSON.stringify(stamped));assert.equal(restored.find(m=>m.id===id).shop,'河口湖');
const merged=ctx.mergeById(restored,[{id:'remote',kind:'purchase',text:'旅伴商品',_u:1}],{});assert.equal(merged.length,4);
ctx.deleteBuy(id);assert(ctx.S.trash[id]);assert(!ctx.buyItems().some(m=>m.id===id));undo();assert(ctx.buyItems().some(m=>m.text==='新口味'&&m.id!==id));assert.equal(ctx.S.memo[0].id,'memo1');
assert(html.includes("m.kind!=='purchase'"));assert(html.includes("else if(m.t==='buy_edit')c=buyModal()"));
// Grouping, backwards compatibility, custom categories and image presentation.
vm.runInContext("buyFilter='all'",ctx);
const photo='data:image/jpeg;base64,YWJj';
ctx.FM={buyName:'乳霜',buyQuantity:1,buyArea:'  銀座  ',buyCategory:'美妝保養',buyShop:'Loft',buyImage:photo};ctx.saveBuy();
ctx.FM={buyName:'鉛筆',buyQuantity:3,buyArea:'銀座',buyCategory:'文具',buyShop:'伊東屋'};ctx.saveBuy();
const cream=ctx.buyItems().find(m=>m.text==='乳霜');assert.equal(cream.area,'銀座');assert.equal(cream.image,photo);
const groups=ctx.buyGroups(ctx.buyItems());assert.equal(groups.filter(([a])=>a==='銀座').length,1);assert.equal(groups.find(([a])=>a==='銀座')[1].length,2);assert.equal(groups.at(-1)[0],'未指定地區');
assert.equal(ctx.buyCategory({}),'其他');assert.equal(ctx.safeBuyImage('javascript:alert(1)'), '');assert.equal(ctx.safeBuyImage('data:image/svg+xml;base64,YWJj'),'');assert.equal(ctx.safeBuyImage('data:image/jpeg;base64,'+'a'.repeat(40001)),'');
assert(ctx.buyCard(cream).includes('class="buy-photo"  ontoggle'));assert(ctx.buyCard(cream).includes('loading="lazy"'));assert(!ctx.buyCard({id:'none',text:'無圖'}).includes('<details'));
vm.runInContext(`buyPhotoOpen.add('${cream.id}')`,ctx);assert(ctx.buyCard(cream).includes('class="buy-photo" open'));
vm.runInContext("buyCategoryFilter='文具'",ctx);assert(ctx.buyView().includes('鉛筆'));assert(!ctx.buyView().includes('乳霜'));
ctx.openBuy(null,cream.id);assert.equal(ctx.FM.buyArea,'銀座');assert.equal(ctx.FM.buyImage,photo);assert(ctx.buyModal().includes('buy-photo-input'));ctx.FM.buyImage='';ctx.saveBuy();assert.equal(ctx.buyItems().find(m=>m.id===cream.id).image,'');
const before=ctx.S.memo.length;ctx.FM={buyName:'等待圖片',buyQuantity:1,buyImageBusy:true};ctx.saveBuy();assert.equal(ctx.S.memo.length,before);
ctx.S.cover='x'.repeat(850000);ctx.FM={buyName:'超出容量',buyQuantity:1};ctx.saveBuy();assert.equal(ctx.S.memo.length,before);delete ctx.S.cover;
// Browser image pipeline mocked at its I/O boundary; cancellation must not leak images into another draft.
let imageHandle,refresh=0,revoked=0;
ctx._refreshHeroContent=()=>refresh++;
ctx.URL={createObjectURL:()=> 'blob:test',revokeObjectURL:()=>revoked++};
ctx.Image=class{constructor(){imageHandle=this;this.naturalWidth=1200;this.naturalHeight=800;}set src(v){this.source=v;}};
ctx.document={createElement:()=>({getContext:()=>({fillRect(){},drawImage(){}}),toDataURL:()=>photo})};
ctx.S.modal={t:'buy_edit'};ctx.FM={buyImage:''};ctx.uploadBuyImage({type:'image/jpeg',size:2000});assert(ctx.FM.buyImageBusy);imageHandle.onload();assert.equal(ctx.FM.buyImage,photo);assert.equal(ctx.FM.buyImageBusy,false);assert.equal(revoked,1);
ctx.uploadBuyImage({type:'image/png',size:2000});ctx.FM={buyImage:''};imageHandle.onload();assert.equal(ctx.FM.buyImage,'');assert.equal(revoked,2);
ctx.uploadBuyImage({type:'image/webp',size:2000});imageHandle.onerror();assert.equal(ctx.FM.buyImageBusy,false);assert.equal(revoked,3);
const beforeInvalid=refresh;ctx.uploadBuyImage({type:'image/svg+xml',size:100});ctx.uploadBuyImage({type:'image/png',size:13*1024*1024});assert.equal(refresh,beforeInvalid);
// Multiple choices preserve drafts, toggle independently and expose their selected state.
const inputs=Object.fromEntries(['category','area','shop','recipients'].map(key=>['buy-'+key,{value:'',maxLength:200}]));
const chip=(field,value)=>({dataset:{field,value},setAttribute(key,value){this[key]=value;}});
const chips=[chip('buyArea','銀座'),chip('buyArea','新宿'),chip('buyRecipients','媽媽')];
ctx.document={getElementById:id=>inputs[id],querySelectorAll:()=>chips};
ctx.FM={buyArea:'銀座',buyNote:'保留備註',buyImage:photo};inputs['buy-area'].value='銀座';
ctx.applyBuyQuick(chips[1]);assert.equal(ctx.FM.buyArea,'銀座、新宿');assert.equal(chips[0]['aria-pressed'],'true');assert.equal(chips[1]['aria-pressed'],'true');
ctx.applyBuyQuick(chips[0]);assert.equal(ctx.FM.buyArea,'新宿');assert.equal(chips[0]['aria-pressed'],'false');
inputs['buy-area'].value=' 自填地區、 自填地區，銀座 ';ctx.applyBuyQuick(chips[1]);assert.equal(ctx.FM.buyArea,'自填地區、銀座、新宿');
ctx.updateBuyQuick('buyArea','銀座');assert.equal(chips[1]['aria-pressed'],'false');assert.equal(ctx.FM.buyNote,'保留備註');assert.equal(ctx.FM.buyImage,photo);
inputs['buy-area'].value='銀座';inputs['buy-area'].maxLength=2;ctx.applyBuyQuick(chips[1]);assert.equal(inputs['buy-area'].value,'銀座');
ctx.FM={buyName:'多區商品',buyQuantity:2,buyArea:'銀座、新宿、銀座',buyCategory:'生活雜貨、伴手禮',buyRecipients:'媽媽、霹靂維德',buyShop:'Loft、唐吉訶德',buyImage:photo};ctx.saveBuy();
const multi=ctx.buyItems().find(m=>m.text==='多區商品');assert.equal(multi.area,'銀座、新宿');assert.equal(multi.recipients,'媽媽、霹靂維德');
ctx.openBuy(null,multi.id);assert.equal(ctx.FM.buyRecipients,'媽媽、霹靂維德');assert.equal(ctx.FM.buyImage,photo);
const multiGroups=ctx.buyGroups([multi]);assert.equal(multiGroups.length,2);assert(multiGroups.every(([,items])=>items.length===1&&items[0].id===multi.id));
vm.runInContext("buyCategoryFilter='伴手禮';buyFilter='all'",ctx);assert(ctx.buyView().includes('多區商品'));assert(ctx.buyView().includes(' / '+ctx.buyItems().length+' 件'));
ctx.toggleMemo(multi.id);assert(ctx.buyGroups([multi]).length===2);assert(ctx.buyItems().find(m=>m.id===multi.id).done);
assert(ctx.buyQuickValues('area').includes('新宿'));assert(!ctx.buyQuickValues('area').includes('銀座、新宿'));
ctx.S.travelers=['霹靂維德','旅伴乙'];const recipientHtml=ctx.buyQuickChoices('buyRecipients','recipients');
assert(recipientHtml.includes('旅伴乙'));assert(recipientHtml.includes('data-value="媽媽" aria-pressed="true"'));assert(ctx.buyCard(multi).includes('幫誰買｜媽媽、霹靂維德'));
assert(!ctx.buyCard({id:'legacy',text:'舊商品'}).includes('幫誰買｜'));
ctx.FM.buyRecipients='<img src=x onerror=alert(1)>';ctx.saveBuy();assert(!ctx.buyCard(ctx.buyItems().find(m=>m.id===multi.id)).includes('<img src=x'));
const recipientMerge=ctx.mergeById(JSON.parse(JSON.stringify(ctx.stampChanges(ctx.S.memo,[]))),[],{});
assert.equal(recipientMerge.find(m=>m.id===multi.id).recipients,ctx.FM.buyRecipients);
console.log('PASS: purchase regressions, multi-select toggling, selected states, manual choices, multi-area grouping, category membership, unique totals, recipients, escaping and sync roundtrip');
